version: '3.8'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    ports:
      - "49201:9200"
      - "49301:9300"
    env_file:
      - .env
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data

  logstash:
    build: logstash_jdbc_input
    env_file:
      - .env
    ports:
      - 49600:9600
      - 45044:5044
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash_data:/logstash_data
